Ui
stakenouchi-cq/Android-BookManager pull request #1
Opened 2017-09-19 08:43 UTC by stakenouchi-cq

2017-09-20 04:11 UTC, ykawakami-cq reviewed
確認お願いします。

2017-09-20 04:11 UTC, ykawakami-cq commented on app/src/main/java/com/caraquri/android_bookmanager/BookAddActivity.java
> +                            public void onDateSet(DatePicker datePicker, int i, int i1, int i2) {
i, i1, i2だとぱっと見分かりにくいので`year` `month` `day` 的な感じのほうが良いかも

2017-09-20 04:11 UTC, ykawakami-cq commented on app/src/main/java/com/caraquri/android_bookmanager/BookListFragment.java
> +        final ArrayList<Book> bookList = new ArrayList<>();
ArrayList固有のメソッドを使用しない場合は、`List<Book> list = new ArrayList<>();`で書くほうがいいようです。
http://www.sejuku.net/blog/14886

2017-09-20 04:11 UTC, ykawakami-cq commented on app/src/main/java/com/caraquri/android_bookmanager/AccountSettingActivity.java
> +    EditText passwordConfirmEditText;
外部からアクセスする必要がなければprivateで！

2017-09-20 04:11 UTC, ykawakami-cq commented on app/src/main/res/layout/activity_account_setting.xml
> +        android:layout_width="368dp"
`match_parent `で良い気がする(？)

2017-09-20 04:11 UTC, ykawakami-cq commented on app/src/main/res/layout/activity_account_setting.xml
> +        android:paddingRight="25dp"
res/values/dimens.xml を作って数値をまとめておくと良いです。
```
<dimen name="activity_padding">25dp</dimen>
<dimen name="activity_margin_top">20dp</dimen>
```
のような感じで。

2017-09-20 08:55 UTC, ykawakami-cq commented on app/src/main/java/com/caraquri/android_bookmanager/CheckUtil.java
> +        return editText.getText().toString().equals("");
`android.text.TextUtils.isEmpty(CharSequence str)` を使うと`null`と`0-length`の両方を判定してくれるので、便利です。
https://developer.android.com/reference/android/text/TextUtils.html#isEmpty(java.lang.CharSequence)

2017-09-20 08:55 UTC, ykawakami-cq commented on app/src/main/java/com/caraquri/android_bookmanager/AccountSettingActivity.java
> +    private Intent intent;
メンバ変数として持っておく必要はないかも。

2017-09-20 08:55 UTC, ykawakami-cq commented on app/src/main/java/com/caraquri/android_bookmanager/BookAddActivity.java
> +                            public void onDateSet(DatePicker datePicker, int year, int month, int day) {
`DatePick.java`へまとめられたら、そっちで共通化させたほうが良いかな

2017-09-20 08:55 UTC, ykawakami-cq commented on app/src/main/java/com/caraquri/android_bookmanager/DatePick.java
> +        java.util.Calendar calendar = java.util.Calendar.getInstance();
`import java.util.Calendar;`
importしてくださいー

2017-09-20 08:55 UTC, ykawakami-cq commented on app/src/main/res/layout/activity_account_setting.xml
> +            android:id="@+id/emailTextView"
idはスネークケースで書くことが多いですー
`email_text_view`
`email_edit_text`
などなど。

2017-09-21 05:43 UTC, ykawakami-cq commented
@stakenouchi-cq 
確認しましたー
大丈夫そうです。

2017-09-21 05:44 UTC, stakenouchi-cq commented
ありがとうございます😃

2017-09-21 08:21 UTC, hyoshimi-cq reviewed
コメントしました！

2017-09-21 08:21 UTC, hyoshimi-cq commented on app/src/main/java/com/caraquri/android_bookmanager/AccountSettingActivity.java
> +        menu.findItem(R.id.menu_save).setVisible(true);
画面ごとにmenuを作っておけば `setVisible()` はしなくて済むよ

2017-09-21 08:21 UTC, hyoshimi-cq commented on app/src/main/java/com/caraquri/android_bookmanager/AccountSettingActivity.java
> +                break;
`onOptionsItemSelected()` の返り値の仕様を確認した方が良さそう
https://developer.android.com/reference/android/app/Activity.html?hl=ja#onOptionsItemSelected(android.view.MenuItem)

もしくは以下のページで `onOptionsItemSelected` と検索すれば見れる
https://developer.android.com/guide/topics/ui/menus.html?hl=ja

2017-09-21 08:21 UTC, hyoshimi-cq commented on app/src/main/java/com/caraquri/android_bookmanager/BookAdapter.java
> +        ((TextView) view.findViewById(R.id.text_sign)).setTextSize(25);
テキストサイズは `xml` で定義できますー

2017-09-21 08:21 UTC, hyoshimi-cq commented on app/src/main/java/com/caraquri/android_bookmanager/BookAdapter.java
> +        ((TextView) view.findViewById(R.id.book_purchase_date)).setText(bookList.get(i).getPurchaseDate());
キャストがあったり同じ処理を書いていたりと自分としては読みにくいかなと思います。なので自分なら一時変数にして以下のようにするかな
```java
TextView title = (TextView) view.findViewById(R.id.book_title);
Book book = bookList.get(i);
title.setText(book.getTitle());
```

人によると思うので、微妙だと思ったらそのままでも大丈夫です。

2017-09-21 08:21 UTC, hyoshimi-cq commented on app/src/main/java/com/caraquri/android_bookmanager/BookAdapter.java
> +        ((TextView) view.findViewById(R.id.book_price)).setText(context.getResources().getString(R.string.price_notation, bookList.get(i).getPrice()));
`Context` にも `getString()` はあるので `context.getString()` で行けるはず

2017-09-21 08:21 UTC, hyoshimi-cq commented on app/src/main/java/com/caraquri/android_bookmanager/BookAddActivity.java
> +        getSupportActionBar().setDisplayHomeAsUpEnabled(true);
`setDisplayHomeAsUpEnabled()` はxmlでも設定できます

2017-09-21 08:21 UTC, hyoshimi-cq commented on app/src/main/java/com/caraquri/android_bookmanager/DatePickerDialogFragment.java
> +                        editText.setText(String.format("%d/%02d/%02d", year, month+1, day));
これは良くないですね。
例えばこの日付のダイアログを他の用途で使用したい時には新たにクラスを作成しないといけなくなります。
なので選択した日付を `EditText` に入れるのではなく選択した日付を伝える `interface` を用意してその `interface` をActivityなどで実装するようにした方がいいです。

2017-09-22 08:18 UTC, hyoshimi-cq commented on app/src/main/java/com/caraquri/android_bookmanager/BookEditFragment.java
> +        String purchaseDate = args.getString("purchaseDate");
`Arguments` のkeyは使用するFragment側に定数として定義しましょう。

2017-09-22 08:18 UTC, hyoshimi-cq commented on app/src/main/java/com/caraquri/android_bookmanager/DatePickerDialogFragment.java
> +        if (this.listener == null) return;
`{}` は必ずつけるようにしましょう。

2017-09-22 09:41 UTC, hyoshimi-cq commented on app/src/main/java/com/caraquri/android_bookmanager/BundleKey.java
> +public enum BundleKey {
enumにするのであればそれを使うFragment（getArguments()する側）に記述した方がいいかな。これだとどこで使うのかがぱっと見わからなくなる。

あとさっき伝えたかったことは↓のような感じです。
```java
public class BookListFragment extends Fragment {

  public void onItemClick() {
    BookEditFragment fragment = new BookEditFragment();
    args.putString(BookEditFragment.ARGS_TITLE, String.valueOf(selectedBook.getTitle()));
    fragment.setArguments(args);
  }
}

----------------------------------------------------------------

public class BookEditFragment extends Fragment {
  public final static String ARGS_TITLE = "args_title";

  public void onViewCreated() {
    String title = getArguments().getString(ARGS_TITLE);
  }
}
```

もしくは以下のようにすればBundleのkeyは `BookEditFragment` だけ知っていればよくなるのでおすすめです。

```java
public class BookEditFragment extends Fragment {
  // ここをprivateにできる
  private final static String ARGS_TITLE = "args_title";

  // 渡したいデータを引数に追加する
  public static BookEditFragment newInstance(String title) {
    Bundle args = new Bundle();
    BookEditFragment fragment = new BookEditFragment();
    args.setString(ARGS_TITLE, title);
    fragment.setArguments(args);
    return fragment;
  }
}
```

わからなければ教えます！

2017-09-22 10:33 UTC, hyoshimi-cq reviewed
コメントしました！
他は大丈夫そうです！

2017-09-22 10:33 UTC, hyoshimi-cq commented on app/src/main/java/com/caraquri/android_bookmanager/BookListFragment.java
> +                transaction.replace(R.id.container, fragment.newInstance(imageString, title, price, purchaseDate));
staticメソッドなので `BookEditFragment. newInstance()` でできます

2017-09-25 02:49 UTC, ghost requested changes

2017-09-25 02:49 UTC, yiino-cq commented on app/src/main/java/com/caraquri/android_bookmanager/AccountSettingActivity.java
> +                AccountSettingActivity.this.finish();
`finish()`と等価じゃない?

2017-09-25 02:49 UTC, yiino-cq commented on app/src/main/java/com/caraquri/android_bookmanager/Book.java
> +    long id;
なぜこれだけアクセス修飾子なし?

2017-09-25 02:49 UTC, yiino-cq commented on app/src/main/java/com/caraquri/android_bookmanager/Book.java
> +    private String imgStr; // 画像をbase64で表現した時の文字列
こういうデータは本来不要でかつデータが大きいのでできればもたないほうが良いです

2017-09-25 02:49 UTC, yiino-cq commented on app/src/main/java/com/caraquri/android_bookmanager/BookAdapter.java
> +public class BookAdapter extends BaseAdapter {
BaseAdapterではなくArrayAdapterが使えないか検討してください
ArrayAdapterはBaseAdapterをリスト形式のアイテムを保つ場合の基本実装を提供しています

2017-09-25 02:49 UTC, yiino-cq commented on app/src/main/java/com/caraquri/android_bookmanager/BookAddActivity.java
> +        return Environment.getExternalStorageState() + "/" + Environment.DIRECTORY_DCIM + "/";
`getExternalStorageState`のドキュメントを読んで下さい

cc: @ykawakami-cq @hyoshimi-cq

2017-09-25 02:49 UTC, yiino-cq commented on app/src/main/java/com/caraquri/android_bookmanager/BookAddActivity.java
> +        if (requestCode == RESULT_PICK_IMAGEFILE && resultCode == Activity.RESULT_OK) {
どちらかというと `REQUEST_PICK_IMAGEFILE `では?

2017-09-25 02:49 UTC, yiino-cq commented on app/src/main/java/com/caraquri/android_bookmanager/BookAddActivity.java
> +            Uri uri = null;
ifよりまえにUriを宣言する必要はないと思います
null初期化も不要です

2017-09-25 02:49 UTC, yiino-cq commented on app/src/main/java/com/caraquri/android_bookmanager/BookAddActivity.java
> +                Log.i("", "Uri: " + uri.toString());
data.getData()がnullの場合ここで落ちます

2017-09-25 02:49 UTC, yiino-cq commented on app/src/main/java/com/caraquri/android_bookmanager/BookAddActivity.java
> +                this.finish();
this. 不要

2017-09-25 02:49 UTC, yiino-cq commented on app/src/main/java/com/caraquri/android_bookmanager/BookAddActivity.java
> +                if (TextUtils.isEmpty(titleEditText.getText()) || !CheckUtil.isNumber(priceEditText) || TextUtils.isEmpty(purchaseDateEditText.getText())) {
`TextUtils`に文字列が数字かどうかをチェックするメソッドもあります

cc: @ykawakami-cq @hyoshimi-cq

2017-09-25 02:49 UTC, yiino-cq commented on app/src/main/java/com/caraquri/android_bookmanager/BookEditFragment.java
> +        Toolbar toolbar = (Toolbar) ((AppCompatActivity) getActivity()).findViewById(R.id.main_toolbar);
`AppCompatActivity `のキャストいらなくない?

2017-09-25 02:49 UTC, yiino-cq commented on app/src/main/java/com/caraquri/android_bookmanager/BookEditFragment.java
> +    private ImageView bookTmb;
Tmbってなに?
androidではやたらと省略する文化はないのでそういうものであれば別の名前にしましょう

2017-09-25 02:49 UTC, yiino-cq commented on app/src/main/java/com/caraquri/android_bookmanager/BookAddActivity.java
> +    public Bitmap getBitmapFromUri(Uri uri) throws IOException {
公開する必要がなければprivate

2017-09-25 02:49 UTC, yiino-cq commented on app/src/main/java/com/caraquri/android_bookmanager/OnDateSetListener.java
> +    public void onDateSet(DatePicker datePicker, int year, int month, int day);
DatePickerのリスナーってもとからあったようなきがするけど

2017-09-25 09:30 UTC, stakenouchi-cq commented on app/src/main/java/com/caraquri/android_bookmanager/Book.java
> +    private String imgStr; // 画像をbase64で表現した時の文字列
書籍のオブジェクトには、画像のPathだけ持つように変更しようと思います

2017-09-25 09:39 UTC, yiino-cq commented
どうでもいいっちゃいいんだけどコミットメッセージを丁寧語にする必要はないです…

2017-09-25 09:54 UTC, yiino-cq commented on app/src/main/java/com/caraquri/android_bookmanager/AccountSettingActivity.java
> +    private final int REQUEST_PERMISSION = 1000;
static

2017-09-25 09:54 UTC, yiino-cq commented on app/src/main/java/com/caraquri/android_bookmanager/AccountSettingActivity.java
> +    private void checkStoragePermission() {
コレ必要だった?
publicなディレクトリに書き込まなければ要らない気がしたけどそんなことなかったっけ

2017-09-25 09:54 UTC, yiino-cq commented on app/src/main/java/com/caraquri/android_bookmanager/BookAdapter.java
>      private List<Book> bookList;
ArrayAdapterならアイテムは持たなくても取ってこれると思う(なぜコンストラクタにアイテムを渡しているかに注目)

2017-09-25 09:54 UTC, yiino-cq commented on app/src/main/java/com/caraquri/android_bookmanager/BookAdapter.java
>      private LayoutInflater layoutInflater = null;
null初期化は不要

2017-09-25 09:54 UTC, yiino-cq commented on app/src/main/java/com/caraquri/android_bookmanager/BookAdapter.java
> +    private Bitmap getBitmapFromAssets(String imagePath) {
繰り返し出てきたら別クラスに切り出すのを考えましょう

2017-09-25 09:55 UTC, yiino-cq commented
あと1コミットで全部つめこまない方がいいです

2017-09-25 10:16 UTC, stakenouchi-cq commented on app/src/main/java/com/caraquri/android_bookmanager/AccountSettingActivity.java
> +    private void checkStoragePermission() {
SDカード上の画像も読込可能とするために、パーミッションを当初追加していたのですが、公式のページで調べてみたら「現在は不要ですが、将来的にAndroidが新しくなった時にこのパーミッションが外部ストレージの読込に必要となる」との記載がありました。
今は必須ではないとのことですが、コードの見栄えを考えると無い方が良いでしょうか？
それともAndroidが新しくなったときに備えて、入れておくべきでしょうか？
https://developer.android.com/training/basics/data-storage/files.html?hl=ja#READ_EXTERNAL_STORAGE

2017-09-25 10:21 UTC, yiino-cq commented on app/src/main/java/com/caraquri/android_bookmanager/AccountSettingActivity.java
> +    private void checkStoragePermission() {
まああって問題があるわけでもないので(どうせ実装の知識も必要になるし)このままで:ok_woman:です

2017-09-26 03:05 UTC, ghost approved these changes
良いと思います!:+1:

2017-09-26 03:05 UTC, yiino-cq commented on app/src/main/java/com/caraquri/android_bookmanager/BookAddActivity.java
> +        bookThumbnail.setImageBitmap(ImageUtil.getBitmapFromAssets(getApplicationContext(), "no_image.png"));
Activity自身もContextです
BookAdapterでわたしてるContextがなんだったかも再チェック

2017-09-26 03:45 UTC, merged